#!/bin/bash
# Fri Jul 5 11:02:18 CEST 2019
# Made by L-F-S
# At the University Of Trento, Italy


###################################
#                                 #
#             STEP 4              #
#       Exploratory analyses      #
#                                 #
###################################

This folder contains i) the python notebooks (.ipynb files)  with preliminary
exploratory analyses propedeutici for step 5
(which is the final step of the 'variants from known effectors' pipeline.)
ii) Scripts for finding a PAM sequence in silico (currently (18/09/2019) failing)

++++++++++++++++++++++++++++++++++
FILES:
|
|-Cas mining Cpf1 example.ipynb
|-cibiobacter cas9 exploratory analyses.ipynb
|-summary.ipynb
|-Coprococcus_Cpf1
|
|-pamsearch/
|
