#!/bin/bash
# 11/06/2019
# Made by L-F-S
# At the University Of Trento, Italy

# run pilercr the samplesample bins
# with default parameters.
WDIR=/shares/CIBIO-Storage/CM/scratch/tmp_projects/signorini_cas/1crisprsearch/test
minced="/home/lorenzo.signorini/utils/jdk-12.0.1/bin/java -jar /home/lorenzo.signorini/1crisprsearch/minced/minced.jar"
cd $WDIR/samplesample
for INFILE in $(ls); do
    echo $INFILE
    ${minced} $INFILE $WDIR/out/${INFILE}.minced.out.txt  ${WDIR}/out/${INFILE}.minced.out.gff &

done


