#!/bin/bash
# Thu Jul 25 16:11:48 CEST 2019
# Made by L-F-S
# At the University Of Trento, Italy

if [ $# -lt 1 ]; then
    echo "cd to /scratchCM/tmp_projects/epasolli_darkmatter/allcontigs\<dataset\>/metabat/genomes_comp50_cont05/prokka/\<sample_ID\>/"
    echo ++++++++++++++++++++++++++++++++++++++++++++
    echo Usage: 
    echo originalsamples \<dataset\>
    exit 1
fi

cd /scratchCM/tmp_projects/epasolli_darkmatter/allcontigs/$1/metabat/genomes_comp50_cont05/prokka/

