#!/bin/bash
# Sun Dec 1 15:48:11 UTC 2019
# Made by L-F-S
# At the University Of Trento, Italy
if [ $# -lt 1 ]; then

	python /home/lorenzo.signorini/cas_mining/9casminer_v2/cas_miner.py -h
else
python /home/lorenzo.signorini/cas_mining/9casminer_v2/cas_miner.py $@
fi
